### ISSUE TITLE
"Black" maps to a monkey

### ISSUE THREAD

**Issue by sakarisson** [Kevinpgalligan/EmojipastaBot#3]
I know there was no negative intention here, but it does seem a bit problematic to me.

I'd be happy to make a PR to remove this mapping.

Real-world example: https://www.reddit.com/r/moviescirclejerk/comments/jvcnsu/holy_shit_holy_shit_im_gonna_cum/gcjjdso/

**Comment by Kevinpgalligan** [comment]
Of course, I'll remove it.

**Comment by Kevinpgalligan** [comment]
Done: https://github.com/Kevinpgalligan/EmojipastaBot/commit/cab0b3394c24905bac72c6e20803261c8948e08c

I'll also remove it from the emojipasta generator on my website.

**Comment by sakarisson** [comment]
Thanks for the quick response and for the fun tool! :)
